debug=true
oauth.consumerKey=M9zbSIMZufdoBxfAjrle0FCn0fAkE
oauth.consumerSecret=RKk8SCWk0fAkEex4alVj1vEKNXBLUKCBRFsVjHgInm6Yf8xVtoHzpn
oauth.accessToken=1070817584839356416-dKE0b7tFnfAkE0MFgCLP4NGMZ0nj4KIH4n
oauth.accessTokenSecret=MfehVCWFqHkqrZs3wxjy0RrfAkEBfNs99nWaHBFDwtfMbI3Ks